Traceback (most recent call last):
  File "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/src/main.py", line 22, in <module>
    from src.data_processing.contextual_chunker import ContextualChunker
  File "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/src/data_processing/contextual_chunker.py", line 8, in <module>
    from vertexai.generative_models import GenerativeModel, Content, Part, GenerationConfig
  File "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/.venv/lib/python3.9/site-packages/vertexai/generative_models/__init__.py", line 19, in <module>
    from vertexai.generative_models._generative_models import (
  File "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/.venv/lib/python3.9/site-packages/vertexai/generative_models/_generative_models.py", line 68, in <module>
    from PIL import Image as PIL_Image  # pylint: disable=g-import-not-at-top
  File "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/.venv/lib/python3.9/site-packages/PIL/Image.py", line 64, in <module>
    from ._binary import i32le, o32be, o32le
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1040, in get_data
TimeoutError: [Errno 60] Operation timed out
Traceback (most recent call last):
  File "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/src/main.py", line 26, in <module>
    from src.chatbot.chatbot import Chatbot
  File "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/src/chatbot/chatbot.py", line 6, in <module>
    from google.cloud import firestore, aiplatform
  File "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/.venv/lib/python3.9/site-packages/google/cloud/firestore/__init__.py", line 18, in <module>
    from google.cloud.firestore_v1 import gapic_version as package_version
  File "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/.venv/lib/python3.9/site-packages/google/cloud/firestore_v1/__init__.py", line 28, in <module>
    from google.cloud.firestore_v1 import types
  File "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/.venv/lib/python3.9/site-packages/google/cloud/firestore_v1/types/__init__.py", line 16, in <module>
    from .aggregation_result import (
  File "/Users/jasonchi/Library/CloudStorage/GoogleDrive-chijunzheng@gmail.com/My Drive/1.Projects/ORAN_RAG/ORAN_RAG_Refactored/.venv/lib/python3.9/site-packages/google/cloud/firestore_v1/types/aggregation_result.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1040, in get_data
TimeoutError: [Errno 60] Operation timed out
